#### **1. 导入numpy库并取别名为np** (★☆☆) 

In [1]:
import numpy as np

#### **2. 打印输出numpy的版本和配置信息** (★☆☆) 

In [2]:
print(np.version)
np.show_config()

<module 'numpy.version' from '/anaconda3/lib/python3.7/site-packages/numpy/version.py'>
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCI

#### **3. 创建长度为10的零向量** (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### **4.  获取数组所占内存大小** (★☆☆) 

In [4]:
z=np.zeros(10)
print(z.size*z.itemsize)

80


#### **5.  怎么用命令行获取numpy add函数的文档说明？

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### **6.  创建一个长度为10的零向量，并把第五个值赋值为1** (★☆☆)

In [6]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### **7.  创建一个值域为10到49的向量** (★☆☆) 

In [12]:
data=np.arange(10,49)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8**.  将一个向量进行反转（第一个元素变为最后一个元素）** (★☆☆) 

In [17]:
data[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### **9.  创建一个3x3的矩阵，值域为0到8**(★☆☆) 

In [23]:
data1=np.arange(9).reshape(3,3)
data1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### **10. 从数组[1, 2, 0, 0, 4, 0]中找出非0元素的位置索引** (★☆☆) 

In [29]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### **11. 创建一个3x3的单位矩阵** (★☆☆) 

In [31]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### **12. 创建一个3x3x3的随机数组**(★☆☆) 

In [33]:
np.random.randn(3,3,3)

array([[[-0.54331185,  1.31161091,  0.9106072 ],
        [ 0.74636901,  1.1198008 ,  1.70155279],
        [ 0.33001948, -0.52087209, -1.44368004]],

       [[-0.01041013, -0.08055482,  0.13805727],
        [-0.01359684, -0.5809096 , -1.65581249],
        [-1.06326337,  0.65917763,  0.3992835 ]],

       [[ 0.75126665, -0.09851193, -1.12580647],
        [ 0.61367881, -1.75693322, -1.24079801],
        [-2.38717183,  0.11935618,  1.37841805]]])

#### **13. 创建一个10x10的随机数组，并找出该数组中的最大值与最小值**(★☆☆) 


In [36]:
data3=np.random.randn(10,10)
data_min=data3.min()
data_max=data.max()
print(data_max,data_min)

48 -2.0992500240198337


#### **14. 创建一个长度为30的随机向量，并求它的平均值** (★☆☆) 

In [40]:
data4=np.random.randn(30)
data4.mean()

-0.26764631919932963

#### **15. 创建一个2维数组，该数组边界值为1，内部的值为0** (★☆☆) 

In [42]:
data5=np.ones((10,10))
data5[1:-1,1:-1]=0
data5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### **16. 如何用0来填充一个数组的边界？** (★☆☆) 

In [44]:
data6= np.ones((5,5))
data6= np.pad(data6, pad_width=1, mode='constant', constant_values=0)
data6

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### **17. 下面表达式运行的结果是什么？**(★☆☆) 

In [51]:
0 * np.nan

nan

In [52]:
np.nan == np.nan


False

In [53]:
np.inf > np.nan


False

In [54]:
np.nan - np.nan


nan

In [55]:
0.3 == 3 * 0.1

False

#### **18. 创建一个5x5的矩阵，且设置值1, 2, 3, 4在其对角线下面一行**(★☆☆) 

In [56]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### **19. 创建一个8x8的棋盘矩阵（填充为棋盘样式）** (★☆☆) 

In [58]:
data7= np.zeros((8,8),dtype=int)
data7[1::2,::2] = 1
data7[::2,1::2] = 1
data7

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])


#### **20. 思考一下形状为(6, 7, 8)的数组的形状，且第100个元素的索引(x, y, z)分别是什么？**(★☆☆) 

In [59]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### **21. 用tile函数创建一个8x8的棋盘矩阵**(★☆☆) 

In [60]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### **22. 对5x5的随机矩阵进行归一化** (★☆☆) 

In [67]:
data8 = np.random.random((5,5))
data8_max, data8_min = data8.max(), data8.min()
data_8 = (data8 - data8_min)/(data8_max - data8_min)
data_8

array([[0.53103759, 0.96442261, 0.36171436, 0.90187411, 0.63501863],
       [0.74750333, 0.47955107, 0.        , 0.74921398, 0.9765557 ],
       [0.08622293, 0.77395568, 0.0013839 , 0.99343309, 0.70708513],
       [1.        , 0.27054706, 0.61673342, 0.02684475, 0.34913091],
       [0.73767951, 0.90223572, 0.20987643, 0.65464436, 0.79833322]])

#### **23. 创建一个dtype来表示颜色(RGBA)** (★☆☆) 

In [68]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### **24. 一个5x3的矩阵和一个3x2的矩阵相乘，结果是什么？**(★☆☆) 

In [ ]:
np.dot(np.ones((5,3)), np.ones((3,2)))

#### **25. 给定一个一维数组把它索引从3到8的元素进行取反** (★☆☆) 

In [69]:
data9 = np.arange(11)
data9[(3 < data9) & (data9<= 8)] *= -1
data9

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### **26. 下面的脚本的结果是什么？** (★☆☆) 

In [70]:
print(sum(range(5),-1))

9


In [71]:
from numpy import *
print(sum(range(5),-1))

10


#### **27. 关于整形的向量Z下面哪些表达式正确？** (★☆☆)

In [76]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [77]:
Z = np.arange(5)
Z ** Z  

array([  1,   1,   4,  27, 256])

In [78]:
 Z= np.arange(5)
2 << Z >> 2  # false

array([0, 1, 2, 4, 8])

In [79]:
Z = np.arange(5)
Z <- Z  

array([False, False, False, False, False])

In [80]:
Z = np.arange(5)
1j*Z 

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [81]:
Z = np.arange(5)
Z/1/1   

array([0., 1., 2., 3., 4.])

In [83]:
Z = np.arange(5)
Z<Z>Z  

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### **28. 下面表达式的结果分别是什么？** (★☆☆)

In [84]:
np.array(0) / np.array(0)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [85]:
np.array(0) // np.array(0)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [86]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### **29. 如何从零位开始舍入浮点数组？** (★☆☆) 

In [87]:
data_10= np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(data_10)),data_10)

array([ 6., -8.,  1.,  3.,  3., -5., 10., -3., -4.,  6.])

#### **30. 如何找出两个数组公共的元素?** (★☆☆) 

In [88]:
data_1 = np.random.randint(0,10,10)
data_2 = np.random.randint(0,10,10)
np.intersect1d(data_1,data_2)

array([1, 3, 8])

#### **31. 如何忽略numpy的警告信息（不推荐）?** (★☆☆) 

#### **32. 下面的表达式是否为真?** (★☆☆) 

In [89]:
np.sqrt(-1) == np.emath.sqrt(-1) 

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### **33. 如何获得昨天，今天和明天的日期?** (★☆☆)

In [90]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today= np.datetime64('today', 'D')
tomorrow= np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### **34. 怎么获得所有与2016年7月的所有日期?** (★★☆)

In [91]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### **35. 如何计算 ((A+B)\*(-A/2)) (不使用中间变量)?** (★★☆) 

In [92]:
a= np.ones(3)*1
b= np.ones(3)*2
c= np.ones(3)*3
(a+b)/b

array([1.5, 1.5, 1.5])

#### **36. 用5种不同的方法提取随机数组中的整数部分** (★★☆) 

#### **37. 创建一个5x5的矩阵且每一行的值范围为从0到4** (★★☆) 

In [97]:
data_1 = np.zeros((5,5))
data_1+= np.arange(5)
data_1

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### **38. 如何用一个生成10个整数的函数来构建数组** (★☆☆) 

#### **39. 创建一个大小为10的向量， 值域为0到1，不包括0和1** (★★☆) 

In [100]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### **40. 创建一个大小为10的随机向量，并把它排序** (★★☆) 

In [102]:
a=np.random.random(10)
a.sort()

#### **41. 对一个小数组进行求和有没有办法比np.sum更快?** (★★☆) 

In [103]:
b= np.arange(10)
np.add.reduce(b)

45

#### **42. 如何判断两和随机数组相等** (★★☆) 

In [106]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
A==B

array([False, False,  True, False, False])

#### **43. 把数组变为只读** (★★☆) 

#### **44. 将一个10x2的笛卡尔坐标矩阵转换为极坐标** (★★☆) 

#### **45. 创建一个大小为10的随机向量并且将该向量中最大的值替换为0**(★★☆) 

In [107]:
a=np.random.random(10)
a[a.argmax()] = 0

#### **46. 创建一个结构化数组，其中`x`和`y`坐标覆盖`[0, 1]x[1, 0]`区域** (★★☆) 

In [108]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))


####  4**7. 给定两个数组`X`和`Y`，构造柯西(Cauchy)矩阵C ($C_{ij}=\frac{1}{x_i-y_j}$)** (★★☆) 

#####  (提示: np.subtract.outer)

In [109]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
np.linalg.det(C)


3638.1636371179666

#### **48. 打印每个numpy 类型的最小和最大可表示值** (★★☆) 

In [110]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### **49. 如何打印数组中所有的值？**(★★☆) m

In [113]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

#### **50. 如何在数组中找到与给定标量接近的值?** (★★☆) 

In [114]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

26


#### **51. 创建表示位置(x, y)和颜色(r, g, b, a)的结构化数组** (★★☆) 

In [115]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
Z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### **52. 思考形状为(100, 2)的随机向量，求出点与点之间的距离** (★★☆) 

In [116]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.96762346 0.91683036 0.31704443 1.11333947 0.08475317
  0.73981328 0.96208786 0.56528143 0.52918129]
 [0.96762346 0.         0.64316248 0.68698555 0.1479588  0.89034107
  0.52031932 0.17522017 0.55151557 0.49056093]
 [0.91683036 0.64316248 0.         0.82168431 0.69265489 0.83596552
  0.98301133 0.79825891 0.89135925 0.47076269]
 [0.31704443 0.68698555 0.82168431 0.         0.83494219 0.26548332
  0.42971841 0.65627449 0.2529314  0.35502801]
 [1.11333947 0.1479588  0.69265489 0.83494219 0.         1.0351077
  0.64294582 0.26150687 0.6926531  0.62325099]
 [0.08475317 0.89034107 0.83596552 0.26548332 1.0351077  0.
  0.69504379 0.89272807 0.51837047 0.44489197]
 [0.73981328 0.52031932 0.98301133 0.42971841 0.64294582 0.69504379
  0.         0.38746194 0.17688367 0.56728992]
 [0.96208786 0.17522017 0.79825891 0.65627449 0.26150687 0.89272807
  0.38746194 0.         0.46642583 0.55448766]
 [0.56528143 0.55151557 0.89135925 0.2529314  0.6926531  0.51837047
  0.17688367 0.466425

#### **53. 如何将类型为float(32位)的数组类型转换位integer(32位)?** (★★☆) 

In [118]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)


#### **54. 如何读取下面的文件?** (★★☆) 

#### **55. numpy数组枚举(enumerate)的等价操作?** (★★☆) 

In [119]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### **56. 构造一个二维高斯矩阵**(★★☆) 

In [120]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### **57. 如何在二维数组的随机位置放置p个元素?** (★★☆) 

In [122]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### **58. 减去矩阵每一行的平均值** (★★☆) 

In [123]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.21317017 -0.3905609   0.15176307 -0.00831664  0.23361301  0.09621368
  -0.00563147 -0.13121212  0.16099789  0.10630365]
 [-0.45464691 -0.05701452  0.20994564 -0.05590283 -0.05403704 -0.05734334
   0.24867193  0.38002584 -0.06526324 -0.09443551]
 [ 0.0423667  -0.02641765  0.1608676   0.02312821 -0.30093197  0.3343302
  -0.14503617 -0.07013556 -0.22551456  0.2073432 ]
 [ 0.37545275 -0.13485739 -0.24565923  0.16480463 -0.02031475  0.15276797
   0.26699065 -0.33728105 -0.38129309  0.1593895 ]
 [-0.36268885  0.52433245 -0.23042811 -0.32774257 -0.16871121 -0.25600535
  -0.3332536   0.23837918  0.34675333  0.56936474]]


#### **59. 如何对数组通过第n列进行排序?** (★★☆) 

In [124]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[1 6 4]
 [6 6 9]
 [4 6 5]]
[[1 6 4]
 [6 6 9]
 [4 6 5]]


#### **60. 如何判断一个给定的二维数组存在空列?** (★★☆) 

In [125]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


#### **61. 从数组中找出与给定值最接近的值** (★★☆) 

In [126]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5456976008870686


#### **62. 思考形状为(1, 3)和(3, 1)的两个数组形状，如何使用迭代器计算它们的和?** (★★☆) 

In [127]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### **63. 创建一个具有name属性的数组类** (★★☆) 

In [128]:
 class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### **64. 给定一个向量，如何让在第二个向量索引的每个元素加1(注意重复索引)?** (★★★) 

In [129]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[2. 5. 2. 3. 4. 2. 3. 3. 4. 2.]


#### **65. 如何根据索引列表`I`将向量`X`的元素累加到数组`F`?** (★★★) 

In [130]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### **66. 思考(dtype = ubyte)的(w, h, 3)图像，计算唯一颜色的值**(★★★) 

In [131]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


#### **67. 思考如何求一个四维数组最后两个轴的数据和**(★★★) 

#### 68. **考虑一维向量D，如何使用相同大小的向量S来计算D的子集的均值，其描述子集索引？**  (★★★) 

In [133]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.443415
1    0.357424
2    0.436312
3    0.693451
4    0.331540
5    0.467134
6    0.488518
7    0.479017
8    0.460117
9    0.363169
dtype: float64


#### 69. **如何获得点积的对角线？** (★★★) 

In [134]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)

array([2.05616355, 0.512144  , 1.31697278, 1.64266837, 0.91458642])

#### **70.考虑向量[1,2,3,4,5]，如何建立一个新的向量，在每个值之间交错有3个连续的零？** (★★★) 


In [135]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### **71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？** (★★★) 

In [136]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### **72. 如何对一个数组中任意两行做交换?** (★★★) 

In [137]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### **73. 思考描述10个三角形（共享顶点）的一组10个三元组，找到组成所有三角形的唯一线段集** (★★★) 

In [138]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 75) ( 0, 78) ( 5, 28) ( 5, 70) (10, 27) (10, 41) (12, 41) (12, 92)
 (25, 51) (25, 71) (27, 41) (27, 94) (27, 96) (28, 70) (29, 67) (29, 96)
 (41, 92) (43, 50) (43, 86) (45, 50) (45, 63) (47, 68) (47, 76) (50, 63)
 (50, 86) (51, 71) (67, 96) (68, 76) (75, 78) (94, 96)]


#### **74. 给定一个二进制的数组`C`，如何生成一个数组`A`满足`np.bincount(A)==C`?** (★★★) 

In [139]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


#### **75. 如何通过滑动窗口计算一个数组的平均数?** (★★★) 

In [140]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### **76. 思考以为数组Z，构建一个二维数组，其第一行是(Z\[0\],Z\[1\],Z\[2\])， 然后每一行移动一位，最后一行为 (Z\[-3\],Z\[-2\],Z\[-1\])** (★★★) 

#(**提示**: from numpy.lib import stride\_tricks)

In [141]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### **77. 如何对布尔值取反，或改变浮点数的符号(`sign`)?** (★★★) 

In [143]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [144]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.27213756,  0.27385051,  0.66137271, -0.65629102, -0.06834889,
        0.21143066, -0.86893476,  0.21868006,  0.42830946,  0.76385313,
       -0.71446809,  0.71308917,  0.42566465, -0.13934551, -0.12359904,
       -0.44148614, -0.33219193,  0.21896859, -0.69034611,  0.98917322,
       -0.83829894, -0.22904498, -0.15478044, -0.17303123,  0.20214336,
        0.01297216,  0.21403463,  0.68386168, -0.68426296,  0.2860811 ,
       -0.23902134,  0.90088428,  0.23095896, -0.5833604 , -0.39540183,
       -0.2181183 , -0.27076367, -0.53068579,  0.27228017, -0.97759823,
        0.62591813,  0.39674222, -0.1467731 ,  0.19837911,  0.65297766,
       -0.35077594, -0.67923981,  0.19677792,  0.493945  , -0.0291878 ,
       -0.18498683, -0.21809245, -0.44050049,  0.11681823,  0.58760151,
        0.60532047, -0.73258914,  0.13746321, -0.27993231,  0.57626446,
       -0.74767729,  0.12721783, -0.29714283, -0.11458829, -0.35942703,
       -0.1461123 , -0.96772479, -0.62358108, -0.64431215, -0.41

#### **78. 思考两组点集`P0`和`P1`去描述一组线(二维)和一个点`p`,如何计算点`p`到每一条线 i `(P0[i],P1[i])`的距离？** (★★★)

In [145]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 5.67230373  4.903456    3.60191214  4.47260831  7.23927796  5.23169533
  3.97595688 12.0997615   5.46451335  8.19362132]


#### **79. 考虑两组点集`P0`和`P1`去描述一组线(二维)和一组点集`P`，如何计算每一个点 `j(P[j])` 到每一条线 i `(P0[i],P1[i])`的距离?** (★★★)

In [146]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[5.37222357e-01 3.12603113e+00 7.12400802e+00 2.56461647e+00
  4.75302498e+00 5.21193550e+00 6.61268547e+00 2.07804868e+00
  1.05023425e+01 1.99677198e+00]
 [1.29893757e+00 1.19762379e+00 1.41305651e+00 2.78604229e+00
  1.96663110e+00 3.52183370e+00 4.59650536e+00 3.65536985e+00
  6.32904095e+00 3.35352153e+00]
 [8.14398395e+00 6.45605305e+00 1.85948742e+00 6.77879153e+00
  5.71274698e+00 1.30094402e+01 1.39743339e+01 2.55296707e+00
  7.60557977e-01 1.30771366e+00]
 [1.00674530e+01 9.36787818e+00 1.39937038e-02 9.29121881e+00
  8.75049864e+00 1.49952917e+01 1.58182038e+01 4.22866141e+00
  2.18341371e+00 7.27108655e-01]
 [6.73897608e+00 8.66186518e-01 1.68234946e+00 7.46947716e+00
  4.23098371e+00 1.86585477e+00 9.03267754e-01 7.07564789e+00
  6.88454993e+00 8.28146692e+00]
 [4.70047911e+00 1.02517517e+01 1.02653897e+01 2.87615358e+00
  4.03132001e+00 4.21100695e-01 8.23829386e-01 1.53549073e+01
  2.42895783e+00 1.41332694e+01]
 [6.37020987e+00 5.15984571e+00 5.96581106e+00 5.84300224e


#### **80. 思考一个任意的数组，编写一个函数，该函数提取一个具有固定形状的子部分，并以一个给定的元素为中心(在该部分填充值)** (★★★) 


#### **81. 考虑一个数组`Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]`,如何生成一个数组`R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]`?** (★★★) 

In [148]:
 Z= np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### **82. 计算矩阵的秩** (★★★) 

In [149]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


#### **83. 如何找出数组中出现频率最高的值?**(★★★) 

In [150]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

3



#### **84. 从一个`10x10`的矩阵中提取出连续的`3x3`区块**(★★★) 

In [151]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[4 3 2]
   [0 3 1]
   [4 3 1]]

  [[3 2 4]
   [3 1 1]
   [3 1 2]]

  [[2 4 0]
   [1 1 0]
   [1 2 4]]

  [[4 0 2]
   [1 0 2]
   [2 4 2]]

  [[0 2 2]
   [0 2 2]
   [4 2 0]]

  [[2 2 0]
   [2 2 2]
   [2 0 1]]

  [[2 0 0]
   [2 2 2]
   [0 1 3]]

  [[0 0 2]
   [2 2 1]
   [1 3 1]]]


 [[[0 3 1]
   [4 3 1]
   [1 3 1]]

  [[3 1 1]
   [3 1 2]
   [3 1 1]]

  [[1 1 0]
   [1 2 4]
   [1 1 0]]

  [[1 0 2]
   [2 4 2]
   [1 0 3]]

  [[0 2 2]
   [4 2 0]
   [0 3 4]]

  [[2 2 2]
   [2 0 1]
   [3 4 4]]

  [[2 2 2]
   [0 1 3]
   [4 4 4]]

  [[2 2 1]
   [1 3 1]
   [4 4 1]]]


 [[[4 3 1]
   [1 3 1]
   [3 3 2]]

  [[3 1 2]
   [3 1 1]
   [3 2 2]]

  [[1 2 4]
   [1 1 0]
   [2 2 1]]

  [[2 4 2]
   [1 0 3]
   [2 1 4]]

  [[4 2 0]
   [0 3 4]
   [1 4 3]]

  [[2 0 1]
   [3 4 4]
   [4 3 2]]

  [[0 1 3]
   [4 4 4]
   [3 2 3]]

  [[1 3 1]
   [4 4 1]
   [2 3 2]]]


 [[[1 3 1]
   [3 3 2]
   [2 0 4]]

  [[3 1 1]
   [3 2 2]
   [0 4 1]]

  [[1 1 0]
   [2 2 1]
   [4 1 4]]

  [[1 0 3]
   [2 1 4]
   [1 4 2]]

  [[0 3 4]
   


#### **85.创建一个满足 `Z[i,j] == Z[j,i]`的二维数组子类** (★★★) 

In [152]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 1 14 11 13 14]
 [14  1  3  8  9]
 [11  3  3 42 11]
 [13  8 42  8 10]
 [14  9 11 10  2]]



#### **86. 考虑p个 `nxn` 矩阵和一组形状为`(n,1)`的向量，如何直接计算p个矩阵的乘积`(n,1)`?** (★★★) 

In [154]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]



#### **87. 对于一个`16x16`的数组，如何得到一个区域的和(区域大小为`4x4`)?** (★★★) 

In [155]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]



#### **88. 如何利用`numpy`数组实现Game of Life?** (★★★)

In [156]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])


    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### **89. 如何找到一个数组的第n个最大值?**  (★★★) 

In [158]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]



#### **90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)**

In [159]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### **91. 如何从一个常规数组中创建记录数组(`record array`)?** (★★★) 


In [160]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]



#### **92. 思考一个大向量`Z`, 用三种不同的方法计算它的立方** (★★★) 

In [161]:
x = np.random.rand()
np.power(x,3)

0.5609028539667064


#### **93. 考虑两个形状分别为`(8,3)` 和`(2,2)`的数组`A`和`B`. 如何在数组`A`中找到满足包含`B`中元素的行？(不考虑`B`中每行元素顺序)？** (★★★) 

In [162]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 1 2 4 6 7]


#### **94. 思考一个`10x3`的矩阵，如何分解出有不全相同值的行 (如 `[2,2,3]`)**  (★★★)

In [163]:
Z = np.random.randint(0,5,(10,3))
print (Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[3 1 4]
 [0 1 4]
 [1 4 4]
 [1 4 2]
 [4 3 2]
 [4 4 3]
 [2 3 4]
 [4 2 3]
 [1 2 2]
 [2 3 4]]
[[3 1 4]
 [0 1 4]
 [1 4 4]
 [1 4 2]
 [4 3 2]
 [4 4 3]
 [2 3 4]
 [4 2 3]
 [1 2 2]
 [2 3 4]]



#### **95. 将一个整数向量转换为二进制矩阵** (★★★) 

In [164]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]




#### **96. 给定一个二维数组，如何提取出唯一的行?**(★★★) 

In [165]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]



#### **97. 考虑两个向量`A`和`B`，写出用`einsum`等式对应的`inner, outer, sum, mul`函数** (★★★) 

In [166]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

sum
6.033045205389854



#### **98. 考虑一个由两个向量描述的路径`(X,Y)`，如何用等距样例(`equidistant samples`)对其进行采样(`sample`)**(★★★)? 


In [167]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### **99. 给定一个整数n 和一个二维数组X，从X中选择可以被解释为从多n度的多项分布式的行，即这些行只包含整数对n的和.** (★★★) 

In [168]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],[2.0, 0.0, 1.0, 1.0],[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]



#### **100. 对于一个一维数组`X`，计算它boostrapped之后的95%置信区间的平均值.** (★★★) 

In [169]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.25004333  0.07055204]
